%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.8
-module(helloworld_pb).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).



-spec encode_msg(map(),hello_request | hello_reply) -> binary().
encode_msg(Msg, MsgName) ->
    encode_msg(Msg, MsgName, []).


-spec encode_msg(map(),hello_request | hello_reply, list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, MsgName, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      hello_request -> e_msg_hello_request(Msg, TrUserData);
      hello_reply -> e_msg_hello_reply(Msg, TrUserData)
    end.



e_msg_hello_request(Msg, TrUserData) ->
    e_msg_hello_request(Msg, <<>>, TrUserData).


e_msg_hello_request(#{} = M, Bin, TrUserData) ->
    case M of
      #{name := F1} ->
	  begin
	    TrF1 = id(F1, TrUserData),
	    case is_empty_string(TrF1) of
	      true -> Bin;
	      false -> e_type_string(TrF1, <<Bin/binary, 10>>)
	    end
	  end;
      _ -> Bin
    end.

e_msg_hello_reply(Msg, TrUserData) ->
    e_msg_hello_reply(Msg, <<>>, TrUserData).


e_msg_hello_reply(#{} = M, Bin, TrUserData) ->
    case M of
      #{message := F1} ->
	  begin
	    TrF1 = id(F1, TrUserData),
	    case is_empty_string(TrF1) of
	      true -> Bin;
	      false -> e_type_string(TrF1, <<Bin/binary, 10>>)
	    end
	  end;
      _ -> Bin
    end.

e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) ->
    not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
      true -> true;
      false -> string_has_chars(T)
    end;
string_has_chars(B)
    when is_binary(B), byte_size(B) =/= 0 ->
    true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
-ifdef('GPB_FUNCTION_STACK').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason ->
        StackTrace = erlang:get_stacktrace(),
        error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

-endif.

decode_msg_2_doit(hello_request, Bin, TrUserData) ->
    d_msg_hello_request(Bin, TrUserData);
decode_msg_2_doit(hello_reply, Bin, TrUserData) ->
    d_msg_hello_reply(Bin, TrUserData).



d_msg_hello_request(Bin, TrUserData) ->
    dfp_read_field_def_hello_request(Bin, 0, 0,
				     id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_hello_request(<<10, Rest/binary>>,
				 Z1, Z2, F@_1, TrUserData) ->
    d_field_hello_request_name(Rest, Z1, Z2, F@_1,
			       TrUserData);
dfp_read_field_def_hello_request(<<>>, 0, 0, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{name => F@_1}
    end;
dfp_read_field_def_hello_request(Other, Z1, Z2, F@_1,
				 TrUserData) ->
    dg_read_field_def_hello_request(Other, Z1, Z2, F@_1,
				    TrUserData).

dg_read_field_def_hello_request(<<1:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_hello_request(Rest, N + 7,
				    X bsl N + Acc, F@_1, TrUserData);
dg_read_field_def_hello_request(<<0:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_hello_request_name(Rest, 0, 0, F@_1,
				     TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_hello_request(Rest, 0, 0, F@_1, TrUserData);
	    1 ->
		skip_64_hello_request(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_hello_request(Rest, 0, 0, F@_1,
						    TrUserData);
	    3 ->
		skip_group_hello_request(Rest, Key bsr 3, 0, F@_1,
					 TrUserData);
	    5 -> skip_32_hello_request(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_hello_request(<<>>, 0, 0, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{name => F@_1}
    end.

d_field_hello_request_name(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_hello_request_name(Rest, N + 7, X bsl N + Acc,
			       F@_1, TrUserData);
d_field_hello_request_name(<<0:1, X:7, Rest/binary>>, N,
			   Acc, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_hello_request(RestF, 0, 0, NewFValue,
				     TrUserData).

skip_varint_hello_request(<<1:1, _:7, Rest/binary>>, Z1,
			  Z2, F@_1, TrUserData) ->
    skip_varint_hello_request(Rest, Z1, Z2, F@_1,
			      TrUserData);
skip_varint_hello_request(<<0:1, _:7, Rest/binary>>, Z1,
			  Z2, F@_1, TrUserData) ->
    dfp_read_field_def_hello_request(Rest, Z1, Z2, F@_1,
				     TrUserData).

skip_length_delimited_hello_request(<<1:1, X:7,
				      Rest/binary>>,
				    N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_hello_request(Rest, N + 7,
					X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_hello_request(<<0:1, X:7,
				      Rest/binary>>,
				    N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_hello_request(Rest2, 0, 0, F@_1,
				     TrUserData).

skip_group_hello_request(Bin, FNum, Z2, F@_1,
			 TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_hello_request(Rest, 0, Z2, F@_1,
				     TrUserData).

skip_32_hello_request(<<_:32, Rest/binary>>, Z1, Z2,
		      F@_1, TrUserData) ->
    dfp_read_field_def_hello_request(Rest, Z1, Z2, F@_1,
				     TrUserData).

skip_64_hello_request(<<_:64, Rest/binary>>, Z1, Z2,
		      F@_1, TrUserData) ->
    dfp_read_field_def_hello_request(Rest, Z1, Z2, F@_1,
				     TrUserData).

d_msg_hello_reply(Bin, TrUserData) ->
    dfp_read_field_def_hello_reply(Bin, 0, 0,
				   id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_hello_reply(<<10, Rest/binary>>, Z1,
			       Z2, F@_1, TrUserData) ->
    d_field_hello_reply_message(Rest, Z1, Z2, F@_1,
				TrUserData);
dfp_read_field_def_hello_reply(<<>>, 0, 0, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{message => F@_1}
    end;
dfp_read_field_def_hello_reply(Other, Z1, Z2, F@_1,
			       TrUserData) ->
    dg_read_field_def_hello_reply(Other, Z1, Z2, F@_1,
				  TrUserData).

dg_read_field_def_hello_reply(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_hello_reply(Rest, N + 7,
				  X bsl N + Acc, F@_1, TrUserData);
dg_read_field_def_hello_reply(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_hello_reply_message(Rest, 0, 0, F@_1,
				      TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_hello_reply(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_hello_reply(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_hello_reply(Rest, 0, 0, F@_1,
						  TrUserData);
	    3 ->
		skip_group_hello_reply(Rest, Key bsr 3, 0, F@_1,
				       TrUserData);
	    5 -> skip_32_hello_reply(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_hello_reply(<<>>, 0, 0, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{message => F@_1}
    end.

d_field_hello_reply_message(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_hello_reply_message(Rest, N + 7, X bsl N + Acc,
				F@_1, TrUserData);
d_field_hello_reply_message(<<0:1, X:7, Rest/binary>>,
			    N, Acc, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_hello_reply(RestF, 0, 0, NewFValue,
				   TrUserData).

skip_varint_hello_reply(<<1:1, _:7, Rest/binary>>, Z1,
			Z2, F@_1, TrUserData) ->
    skip_varint_hello_reply(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_hello_reply(<<0:1, _:7, Rest/binary>>, Z1,
			Z2, F@_1, TrUserData) ->
    dfp_read_field_def_hello_reply(Rest, Z1, Z2, F@_1,
				   TrUserData).

skip_length_delimited_hello_reply(<<1:1, X:7,
				    Rest/binary>>,
				  N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_hello_reply(Rest, N + 7,
				      X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_hello_reply(<<0:1, X:7,
				    Rest/binary>>,
				  N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_hello_reply(Rest2, 0, 0, F@_1,
				   TrUserData).

skip_group_hello_reply(Bin, FNum, Z2, F@_1,
		       TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_hello_reply(Rest, 0, Z2, F@_1,
				   TrUserData).

skip_32_hello_reply(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		    TrUserData) ->
    dfp_read_field_def_hello_reply(Rest, Z1, Z2, F@_1,
				   TrUserData).

skip_64_hello_reply(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		    TrUserData) ->
    dfp_read_field_def_hello_reply(Rest, Z1, Z2, F@_1,
				   TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) ->
    merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      hello_request ->
	  merge_msg_hello_request(Prev, New, TrUserData);
      hello_reply ->
	  merge_msg_hello_reply(Prev, New, TrUserData)
    end.

merge_msg_hello_request(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
      {_, #{name := NFname}} -> S1#{name => NFname};
      {#{name := PFname}, _} -> S1#{name => PFname};
      _ -> S1
    end.

merge_msg_hello_reply(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
      {_, #{message := NFmessage}} ->
	  S1#{message => NFmessage};
      {#{message := PFmessage}, _} ->
	  S1#{message => PFmessage};
      _ -> S1
    end.


verify_msg(Msg, MsgName) ->
    verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      hello_request ->
	  v_msg_hello_request(Msg, [hello_request], TrUserData);
      hello_reply ->
	  v_msg_hello_reply(Msg, [hello_reply], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-dialyzer({nowarn_function,v_msg_hello_request/3}).
v_msg_hello_request(#{} = M, Path, _) ->
    case M of
      #{name := F1} -> v_type_string(F1, [name | Path]);
      _ -> ok
    end,
    lists:foreach(fun (name) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_hello_request(M, Path, _TrUserData)
    when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   hello_request},
		  M, Path);
v_msg_hello_request(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, hello_request}, X, Path).

-dialyzer({nowarn_function,v_msg_hello_reply/3}).
v_msg_hello_reply(#{} = M, Path, _) ->
    case M of
      #{message := F1} -> v_type_string(F1, [message | Path]);
      _ -> ok
    end,
    lists:foreach(fun (message) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_hello_reply(M, Path, _TrUserData)
    when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   hello_reply},
		  M, Path);
v_msg_hello_reply(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, hello_reply}, X, Path).

-dialyzer({nowarn_function,v_type_string/2}).
v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(lists:append(lists:join(".",
					 lists:map(fun atom_to_list/1,
						   lists:reverse(PathR))))).


-compile({inline,id/2}).
id(X, _TrUserData) -> X.


get_msg_defs() ->
    [{{msg, hello_request},
      [#{name => name, fnum => 1, rnum => 2, type => string,
	 occurrence => optional, opts => []}]},
     {{msg, hello_reply},
      [#{name => message, fnum => 1, rnum => 2,
	 type => string, occurrence => optional, opts => []}]}].


get_msg_names() -> [hello_request, hello_reply].


get_group_names() -> [].


get_msg_or_group_names() ->
    [hello_request, hello_reply].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def(hello_request) ->
    [#{name => name, fnum => 1, rnum => 2, type => string,
       occurrence => optional, opts => []}];
find_msg_def(hello_reply) ->
    [#{name => message, fnum => 1, rnum => 2,
       type => string, occurrence => optional, opts => []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> ['helloworld.Greeter'].


get_service_def('helloworld.Greeter') ->
    {{service, 'helloworld.Greeter'},
     [#{name => 'SayHello', input => hello_request,
	output => hello_reply, input_stream => false,
	output_stream => false, opts => []}]};
get_service_def(_) -> error.


get_rpc_names('helloworld.Greeter') -> ['SayHello'];
get_rpc_names(_) -> error.


find_rpc_def('helloworld.Greeter', RpcName) ->
    'find_rpc_def_helloworld.Greeter'(RpcName);
find_rpc_def(_, _) -> error.


'find_rpc_def_helloworld.Greeter'('SayHello') ->
    #{name => 'SayHello', input => hello_request,
      output => hello_reply, input_stream => false,
      output_stream => false, opts => []};
'find_rpc_def_helloworld.Greeter'(_) -> error.


fetch_rpc_def(ServiceName, RpcName) ->
    case find_rpc_def(ServiceName, RpcName) of
      Def when is_map(Def) -> Def;
      error ->
	  erlang:error({no_such_rpc, ServiceName, RpcName})
    end.


get_package_name() -> helloworld.



gpb_version_as_string() ->
    "4.1.8".

gpb_version_as_list() ->
    [4,1,8].
