# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from priv.protos import hellostreamingworld_pb2 as priv_dot_protos_dot_hellostreamingworld__pb2


class MultiGreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.stream_stream(
        '/hellostreamingworld.MultiGreeter/SayHello',
        request_serializer=priv_dot_protos_dot_hellostreamingworld__pb2.HelloRequest.SerializeToString,
        response_deserializer=priv_dot_protos_dot_hellostreamingworld__pb2.HelloReply.FromString,
        )


class MultiGreeterServicer(object):
  """The greeting service definition.
  """

  def SayHello(self, request_iterator, context):
    """Sends multiple greetings
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MultiGreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.stream_stream_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=priv_dot_protos_dot_hellostreamingworld__pb2.HelloRequest.FromString,
          response_serializer=priv_dot_protos_dot_hellostreamingworld__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hellostreamingworld.MultiGreeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
