# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: priv/protos/matrix.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='priv/protos/matrix.proto',
  package='matrix',
  syntax='proto3',
  serialized_pb=_b('\n\x18priv/protos/matrix.proto\x12\x06matrix\"-\n\x06Matrix\x12\x0b\n\x03\x63ol\x18\x01 \x01(\x05\x12\x0b\n\x03row\x18\x02 \x01(\x05\x12\t\n\x01\x65\x18\x03 \x03(\x05\"-\n\x08Operator\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nfactor_num\x18\x02 \x01(\x05\"P\n\x0fMatrixOpRequest\x12\x1f\n\x07matrixs\x18\x01 \x03(\x0b\x32\x0e.matrix.Matrix\x12\x1c\n\x02op\x18\x02 \x01(\x0b\x32\x10.matrix.Operator\"-\n\nMatrixList\x12\x1f\n\x07matrixs\x18\x01 \x03(\x0b\x32\x0e.matrix.Matrixb\x06proto3')
)




_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='matrix.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col', full_name='matrix.Matrix.col', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row', full_name='matrix.Matrix.row', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e', full_name='matrix.Matrix.e', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=81,
)


_OPERATOR = _descriptor.Descriptor(
  name='Operator',
  full_name='matrix.Operator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='matrix.Operator.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='factor_num', full_name='matrix.Operator.factor_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=128,
)


_MATRIXOPREQUEST = _descriptor.Descriptor(
  name='MatrixOpRequest',
  full_name='matrix.MatrixOpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrixs', full_name='matrix.MatrixOpRequest.matrixs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op', full_name='matrix.MatrixOpRequest.op', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=210,
)


_MATRIXLIST = _descriptor.Descriptor(
  name='MatrixList',
  full_name='matrix.MatrixList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrixs', full_name='matrix.MatrixList.matrixs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=257,
)

_MATRIXOPREQUEST.fields_by_name['matrixs'].message_type = _MATRIX
_MATRIXOPREQUEST.fields_by_name['op'].message_type = _OPERATOR
_MATRIXLIST.fields_by_name['matrixs'].message_type = _MATRIX
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['Operator'] = _OPERATOR
DESCRIPTOR.message_types_by_name['MatrixOpRequest'] = _MATRIXOPREQUEST
DESCRIPTOR.message_types_by_name['MatrixList'] = _MATRIXLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), dict(
  DESCRIPTOR = _MATRIX,
  __module__ = 'priv.protos.matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrix.Matrix)
  ))
_sym_db.RegisterMessage(Matrix)

Operator = _reflection.GeneratedProtocolMessageType('Operator', (_message.Message,), dict(
  DESCRIPTOR = _OPERATOR,
  __module__ = 'priv.protos.matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrix.Operator)
  ))
_sym_db.RegisterMessage(Operator)

MatrixOpRequest = _reflection.GeneratedProtocolMessageType('MatrixOpRequest', (_message.Message,), dict(
  DESCRIPTOR = _MATRIXOPREQUEST,
  __module__ = 'priv.protos.matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrix.MatrixOpRequest)
  ))
_sym_db.RegisterMessage(MatrixOpRequest)

MatrixList = _reflection.GeneratedProtocolMessageType('MatrixList', (_message.Message,), dict(
  DESCRIPTOR = _MATRIXLIST,
  __module__ = 'priv.protos.matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrix.MatrixList)
  ))
_sym_db.RegisterMessage(MatrixList)


# @@protoc_insertion_point(module_scope)
