# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: priv/protos/matrix_op.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from priv.protos import matrix_pb2 as priv_dot_protos_dot_matrix__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='priv/protos/matrix_op.proto',
  package='matrixop',
  syntax='proto3',
  serialized_pb=_b('\n\x1bpriv/protos/matrix_op.proto\x12\x08matrixop\x1a\x18priv/protos/matrix.proto2m\n\x08MatrixOp\x12,\n\x04\x45\x63ho\x12\x0e.matrix.Matrix\x1a\x0e.matrix.Matrix\"\x00(\x01\x30\x01\x12\x33\n\x02Op\x12\x17.matrix.MatrixOpRequest\x1a\x12.matrix.MatrixList\"\x00\x62\x06proto3')
  ,
  dependencies=[priv_dot_protos_dot_matrix__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MATRIXOP = _descriptor.ServiceDescriptor(
  name='MatrixOp',
  full_name='matrixop.MatrixOp',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=67,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='matrixop.MatrixOp.Echo',
    index=0,
    containing_service=None,
    input_type=priv_dot_protos_dot_matrix__pb2._MATRIX,
    output_type=priv_dot_protos_dot_matrix__pb2._MATRIX,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Op',
    full_name='matrixop.MatrixOp.Op',
    index=1,
    containing_service=None,
    input_type=priv_dot_protos_dot_matrix__pb2._MATRIXOPREQUEST,
    output_type=priv_dot_protos_dot_matrix__pb2._MATRIXLIST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATRIXOP)

DESCRIPTOR.services_by_name['MatrixOp'] = _MATRIXOP

# @@protoc_insertion_point(module_scope)
