# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from priv.protos import matrix_pb2 as priv_dot_protos_dot_matrix__pb2


class MatrixOpStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.stream_stream(
        '/matrixop.MatrixOp/Echo',
        request_serializer=priv_dot_protos_dot_matrix__pb2.Matrix.SerializeToString,
        response_deserializer=priv_dot_protos_dot_matrix__pb2.Matrix.FromString,
        )
    self.Op = channel.unary_unary(
        '/matrixop.MatrixOp/Op',
        request_serializer=priv_dot_protos_dot_matrix__pb2.MatrixOpRequest.SerializeToString,
        response_deserializer=priv_dot_protos_dot_matrix__pb2.MatrixList.FromString,
        )


class MatrixOpServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Echo(self, request_iterator, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Op(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MatrixOpServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.stream_stream_rpc_method_handler(
          servicer.Echo,
          request_deserializer=priv_dot_protos_dot_matrix__pb2.Matrix.FromString,
          response_serializer=priv_dot_protos_dot_matrix__pb2.Matrix.SerializeToString,
      ),
      'Op': grpc.unary_unary_rpc_method_handler(
          servicer.Op,
          request_deserializer=priv_dot_protos_dot_matrix__pb2.MatrixOpRequest.FromString,
          response_serializer=priv_dot_protos_dot_matrix__pb2.MatrixList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'matrixop.MatrixOp', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
