# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from priv.protos import python_shell_pb2 as priv_dot_protos_dot_python__shell__pb2


class PythonShellStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Eval = channel.unary_unary(
        '/python_shell.PythonShell/Eval',
        request_serializer=priv_dot_protos_dot_python__shell__pb2.EvalRequest.SerializeToString,
        response_deserializer=priv_dot_protos_dot_python__shell__pb2.StringValue.FromString,
        )


class PythonShellServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Eval(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PythonShellServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Eval': grpc.unary_unary_rpc_method_handler(
          servicer.Eval,
          request_deserializer=priv_dot_protos_dot_python__shell__pb2.EvalRequest.FromString,
          response_serializer=priv_dot_protos_dot_python__shell__pb2.StringValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'python_shell.PythonShell', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
